Repository Catif/LP-PTUT_Scudo, pull requests merged in 2023-04, with the labels that each got.

#60 Fake data generation class and script
  api/composer.json
  api/conf/db.ini.example
  api/public/index.php
  api/public/uploads/images/dark_pfp.svg
  api/public/uploads/images/light_pfp.svg
  api/sql/data_generation.php
  api/sql/scudo_db.sql
  api/sql/scudo_db_demo.sql
  api/sql/scudo_fake.sql
  api/sql/scudo_schema.sql
  api/src/models/Comment.php
  api/src/models/Conversation.php
  api/src/models/Message.php
  api/src/models/User.php
  api/src/services/UserService.php
  api/src/services/utils/FakerGenerator.php
Labels: SQL, API

#66 Front view profile
  api/src/actions/user/GET/UserByIdAction.php
  api/src/models/User.php
  front/index.html
  front/src/assets/css/main.css
  front/src/components/Navbar.vue
  front/src/components/ResourceCard.vue
  front/src/components/ScudoTheming/EditButton.vue
  front/src/components/ScudoTheming/FollowButton.vue
  front/src/components/ScudoTheming/Input.vue
  front/src/components/UserCard.vue
  front/src/components/UserPicture.vue
  front/src/components/Username.vue
  front/src/router/index.js
  front/src/stores/session.js
  front/src/views/EditProfileView.vue
  front/src/views/ExampleView.vue
  front/src/views/LoginView.vue
  front/src/views/ProfileView.vue
  front/src/views/group/GroupEditView.vue
Labels: design

#69 Front api homepage
  api/public/index.php
  api/src/actions/group/GET/GroupsRandomAction.php
  api/src/actions/resource/GET/ResourcesAction.php
  api/src/services/GroupService.php
  api/src/services/ResourceService.php
  api/src/services/UserService.php
  front/index.html
  front/public/assets/lib/RTCMultiConnecion.min.js
  front/public/assets/lib/socket.io.js
  front/public/assets/lib/socket.io.js.map
  front/src/App.vue
  front/src/assets/fonts/icon.css
  front/src/assets/fonts/sykg-zNym6YjUruM-QrEh7-nyTnjDwKNJ_190Fjzag.woff2
  front/src/components/ResourceSection.vue
  front/src/components/ScudoTheming/AsideFeed.vue
  front/src/components/ScudoTheming/MainFeed.vue
  front/src/components/SmallGroupCard.vue
  front/src/main.js
  front/src/views/HomeView.vue
Labels: design, API

#71 Setting view
  api/public/index.php
  api/src/actions/user/POST/PasswordChangeAction.php
  api/src/services/UserService.php
  front/src/router/index.js
  front/src/views/SettingView.vue
Labels: design

#73 Node | Amélioration de la gestion d'erreur
  front/src/views/RecordView.vue
  server-stream/events/disconnect.js
  server-stream/utils/function.js
Labels: bug, node

#74 Nouveau FIX pour develop
  front/src/components/EditTopAppBar.vue
  front/src/components/RecordDisplay.vue
  front/src/components/ResourceDisplay.vue
  front/src/components/ScudoTheming/Button.vue
  front/src/components/ScudoTheming/IconButton.vue
  front/src/components/ScudoTheming/Input.vue
  front/src/components/ScudoTheming/MainFeed.vue
  front/src/router/index.js
  front/src/views/EditProfileView.vue
  front/src/views/EditResourceView.vue
  front/src/views/ResourceView.vue
  front/src/views/group/GroupEditView.vue
Labels: bug
