Repository Catif/LP-PTUT_Scudo, pull requests merged in 2023-02, with the labels that each got.

#26 nouveaux composants ResourceCard et ResourceSection
  front/src/components/ResourceCard.vue
  front/src/components/ResourceSection.vue
Labels: design

#27 Front component modal bottom sheet
  front/src/components/ScudoTheming/BottomSheetScaffold .vue
  front/src/components/ScudoTheming/ModalBottomSheet.vue
Labels: design

#28 Création de la Navbar
  front/public/assets/img/logo-short_dark.svg
  front/public/assets/img/logo-short_light.svg
  front/src/App.vue
  front/src/assets/css/main.css
  front/src/assets/scss/_media-queries.scss
  front/src/assets/scss/_media-query.scss
  front/src/components/Navbar.vue
  front/src/components/Navbar_Search.vue
  front/src/components/ScudoTheming/Icon.vue
  front/src/components/ScudoTheming/Input.vue
  front/src/components/ScudoTheming/Text.vue
  front/src/components/ScudoTheming/TopAppBar.vue
Labels: design

#29 Ajout du composant Follow Button
  front/src/components/FollowButton.vue
  front/src/components/ScudoTheming/FilledButton.vue
  front/src/components/ScudoTheming/IconButton.vue
Labels: design

#30 nouveau composant CommentCard
  front/src/components/AuthorSection.vue
  front/src/components/CommentCard.vue
  front/src/components/ScudoTheming/SmallText.vue
Labels: design

#32 Front correctif color
  front/src/assets/css/main.css
  front/src/assets/scss/_colors.scss
  front/src/components/Navbar.vue
  front/src/components/Navbar_Search.vue
  front/src/components/ProfilePicture.vue
  front/src/components/ScudoTheming/Alert.vue
  front/src/components/ScudoTheming/BottomSheetScaffold .vue
  front/src/components/ScudoTheming/Button.vue
  front/src/components/ScudoTheming/ClickableCard.vue
  front/src/components/ScudoTheming/ClickableFilledCard.vue
  front/src/components/ScudoTheming/FilledButton.vue
  front/src/components/ScudoTheming/FilledCard.vue
  front/src/components/ScudoTheming/FloatingAppButton.vue
  front/src/components/ScudoTheming/Input.vue
  front/src/components/ScudoTheming/ModalBottomSheet.vue
  front/src/components/ScudoTheming/SmallText.vue
  front/src/components/ScudoTheming/Text.vue
  front/src/components/ScudoTheming/Title.vue
  front/src/components/ScudoTheming/TopAppBar.vue
  front/src/components/SmallUsername.vue
  front/src/components/Username.vue
Labels: design

#31 Création des composants UserCard et UserProCard
  front/src/components/ProfilePicture.vue
  front/src/components/ScudoTheming/FollowButton.vue
  front/src/components/ScudoTheming/ProfileStat.vue
  front/src/components/UserCard.vue
  front/src/components/UserProCard.vue
  front/src/stores/utils.js
Labels: design

#35 Front app organisation
  front/src/App.vue
  front/src/components/AuthorSection.vue
  front/src/components/GroupCard.vue
  front/src/components/Navbar.vue
  front/src/components/ResourceCard.vue
  front/src/components/ScudoTheming/AsideFeed.vue
  front/src/components/ScudoTheming/MainFeed.vue
  front/src/router/index.js
  front/src/views/ExampleView.vue
  front/src/views/TestView.vue
Labels: design

#37 Api services actions
  api/conf/db.ini.example
  api/public/index.php
  api/src/actions/conversation/GET/ConversationAction.php
  api/src/actions/conversation/GET/ConversationByIdAction.php
  api/src/actions/group/GET/GroupAction.php
  api/src/actions/group/GET/GroupByIdAction.php
  api/src/actions/group/POST/GroupAction.php
  api/src/actions/resource/GET/ResourceAction.php
  api/src/actions/resource/GET/ResourceByIdAction.php
  api/src/actions/resource/POST/ResourceAction.php
  api/src/actions/user/GET/UserAction.php
  api/src/actions/user/GET/UserByIdAction.php
  api/src/actions/user/POST/RegisterAction.php
  api/src/errors/exceptions/RessourcceNotFoundException.php
  api/src/models/Conversation.php
  api/src/models/Resource.php
  api/src/services/CommentService.php
  api/src/services/ConversationService.php
  api/src/services/GroupService.php
  api/src/services/MessageService.php
  api/src/services/ResourceService.php
  api/src/services/UserService.php
Labels: API

#36 nouveau composant Description
  front/src/components/Description.vue
Labels: design

#39 add alert LIVE to ResourceSection
  front/src/components/AuthorSection.vue
  front/src/components/CommentCard.vue
  front/src/components/ProfilePicture.vue
  front/src/components/ResourceSection.vue
  front/src/components/SmallUsername.vue
  front/src/components/UserCard.vue
  front/src/components/UserProCard.vue
  front/src/components/Username.vue
Labels: design

#40 Ajout d'une classe de formatage des objects
  api/src/actions/user/POST/RegisterAction.php
  api/src/models/Conversation.php
  api/src/models/Ressource.php
  api/src/services/utils/FormatterObject.php
Labels: API

#44 Ajout d'un token à l'inscription + Hashage du Mot de passe
  api/.gitignore
  api/composer.json
  api/src/actions/user/GET/UsersAction.php
  api/src/actions/user/POST/RegisterAction.php
  api/src/models/Authorization.php
  api/src/models/User.php
  api/src/services/AuthorizationService.php
  api/src/services/UserService.php
Labels: API

#43 Front fix resource card
  front/src/components/AuthorSection.vue
  front/src/components/ResourceCard.vue
  front/src/components/ResourceSection.vue
  front/src/views/ExampleView.vue
Labels: design

#46 Création d'une route de connexion
  api/public/index.php
  api/src/actions/user/GET/UserByIdAction.php
  api/src/actions/user/GET/UsersAction.php
  api/src/actions/user/POST/LoginAction.php
  api/src/actions/user/POST/RegisterAction.php
  api/src/services/AuthorizationService.php
  api/src/services/UserService.php
Labels: API

#45 Front component création de contenu
  front/src/components/DefaultTopAppBar.vue
  front/src/components/Navbar.vue
  front/src/components/ResourceSection.vue
  front/src/components/ScudoTheming/AsideFeed.vue
  front/src/components/ScudoTheming/MainFeed.vue
  front/src/components/ScudoTheming/ModalBottomSheet.vue
  front/src/components/ScudoTheming/TopAppBar.vue
  front/src/components/SearchTopAppBar.vue
  front/src/views/ExampleView.vue
  front/src/views/TestView.vue
Labels: design

#47 Front component add group
  front/src/components/AddGroup.vue
  front/src/components/ResourceCard.vue
Labels: design

#48 Front function from parent
  front/src/App.vue
  front/src/components/DefaultTopAppBar.vue
  front/src/components/Navbar.vue
  front/src/components/ScudoTheming/ModalBottomSheet.vue
Labels: design

#49 gestion TopAppBar mobileOnly
  front/src/components/DefaultTopAppBar.vue
  front/src/components/ScudoTheming/TopAppBar.vue
Labels: design

#50 Mise à jour des routes API : Register et Login
  .gitignore
  api/public/index.php
  api/src/actions/user/GET/UserByIdAction.php
  api/src/actions/user/GET/UsersAction.php
  api/src/actions/user/PATCH/UserAction.php
  api/src/actions/user/POST/RegisterAction.php
  api/src/services/UserService.php
Labels: API

#52 Ajout des routes pour la tables Resources
  api/public/index.php
  api/src/actions/resource/GET/ResourceAction.php
  api/src/actions/resource/GET/ResourceByIdAction.php
  api/src/actions/resource/GET/ResourcesAction.php
  api/src/actions/resource/PATCH/ResourceAction.php
  api/src/actions/resource/POST/ResourceAction.php
  api/src/actions/resource/POST/ResourceGroupShareAction.php
  api/src/models/Group.php
  api/src/models/Resource.php
  api/src/models/User.php
  api/src/services/AuthorizationService.php
  api/src/services/GroupService.php
  api/src/services/ResourceService.php
  api/src/services/UserService.php
Labels: API

#56 Fix user + authorization
  api/src/actions/comment/POST/CommentAction.php
  api/src/actions/group/DELETE/GroupUnfollowAction.php
  api/src/actions/group/POST/GroupAction.php
  api/src/actions/group/POST/GroupFollowAction.php
  api/src/actions/resource/GET/ResourceByIdAction.php
  api/src/actions/resource/PATCH/ResourceAction.php
  api/src/actions/resource/POST/ResourceAction.php
  api/src/actions/resource/POST/ResourceGroupShareAction.php
  api/src/actions/user/DELETE/DisconnectAction.php
  api/src/actions/user/DELETE/UnfollowAction.php
  api/src/actions/user/GET/UserByIdAction.php
  api/src/actions/user/PATCH/UserAction.php
  api/src/actions/user/POST/FollowAction.php
  api/src/actions/user/POST/RegisterAction.php
Labels: bug, API

#57 Front_view_login + Front_view_register + Api_correctif_result + Correctif erreurs CORS
  api/composer.lock
  api/public/index.php
  api/src/actions/conversation/GET/ConversationByIdAction.php
  api/src/actions/group/DELETE/GroupUnfollowAction.php
  api/src/actions/group/GET/GroupByIdAction.php
  api/src/actions/group/GET/GroupResourceAction.php
  api/src/actions/group/GET/GroupsAction.php
  api/src/actions/group/PATCH/GroupAction.php
  api/src/actions/group/POST/GroupAction.php
  api/src/actions/group/POST/GroupFollowAction.php
  api/src/actions/resource/GET/ResourceByIdAction.php
  api/src/actions/resource/GET/ResourcesAction.php
  api/src/actions/resource/PATCH/ResourceAction.php
  api/src/actions/user/DELETE/DisconnectAction.php
  api/src/actions/user/DELETE/UnfollowAction.php
  api/src/actions/user/GET/UserResourcesAction.php
  api/src/actions/user/GET/UsersAction.php
  api/src/actions/user/POST/FollowAction.php
  api/src/actions/user/POST/LoginAction.php
  api/src/actions/user/POST/RegisterAction.php
  api/src/services/UserService.php
  api/src/services/utils/FormatterAPI.php
  docker-compose.yml
  front/src/App.vue
  front/src/components/ScudoTheming/Input.vue
  front/src/main.js
  front/src/router/index.js
  front/src/stores/session.js
  front/src/views/ExampleView.vue
  front/src/views/LoginView.vue
  front/src/views/RegisterView.vue
Labels: bug, enhancement, design, API

#58 patch resourceById / ajout des comments
  api/src/actions/resource/GET/ResourceByIdAction.php
  api/src/actions/user/POST/RegisterAction.php
  api/src/models/Comment.php
  api/src/models/Resource.php
  api/src/services/ResourceService.php
  api/src/services/UserService.php
Labels: bug, API

#61 Front register vue
  api/src/actions/user/POST/RegisterAction.php
  front/src/App.vue
  front/src/components/ScudoTheming/Input.vue
  front/src/components/ScudoTheming/MainFeed.vue
  front/src/stores/session.js
  front/src/views/LoginView.vue
  front/src/views/RegisterView.vue
Labels: design

#62 correctif connection et inscription suite à la mise à jour de l'API
  front/src/views/LoginView.vue
Labels: bug

#65 Création d'une route pour l'upload de fichier
  api/public/index.php
  api/src/actions/general/POST/UploadAction.php
Labels: API
